pub mod credential_file;
pub mod credential_linux;
pub mod credential_macos;
pub mod credential_registry;
pub mod credential_windows;
pub mod detector;
pub mod diagnostics;
pub mod fs_secure;
pub mod inspect;
pub mod locator;
pub mod lock;
pub mod vault;

pub use credential_file::FileCredentialStore;
pub use credential_linux::LinuxKeyringCredentialStore;
pub use credential_macos::MacKeychainCredentialStore;
pub use credential_registry::{CredentialDiscoveryRegistry, CredentialDiscoveryRule};
pub use credential_windows::WindowsCredentialStore;
pub use detector::AuthJsonSessionDetector;
pub use diagnostics::{StoreDiagnostic, default_store_diagnostics};
pub use locator::{AppPaths, PathResolver};
pub use lock::GlobalSwitchLock;
pub use vault::LocalProfileVault;
